# s=open('demo.txt',mode='r')
# print(s.read())
# s.close()
# s=open('demo.txt',mode='a')
# s.write(" Hello This is write handling")
# s.close()
s=open('demo.txt',mode='w+')
s.write("hello")
s.seek(0)
print(s.read())
s.close()
# s=open('demo.txt',mode='r+')
# print(s.read())
# s.write("HI ")
# s.seek(0)
# print(s.read())
# s.close()